### ISSUE TITLE
opentelemetry-semantic-conventions causes version conflicts with older instrumentation libraries

### ISSUE THREAD

**Issue by nemoshlag** [open-telemetry/opentelemetry-python-contrib#1168] opened 2022-06-28 14:53 UTC
**Is your feature request related to a problem?**
Whenever opentelemetry-python-contrib is being released - a corresponding opentelemetry-semantic-conventions is created and released as well. For a user who wants to update a single instrumented library, this causes an overlay because the new semantic-conventions lib doesn't support the previous instrumented libraries.

**Describe the solution you'd like**
I wish I could update a single opentelemetry-instrumentation library without having to update all other instrumentations as well.

**Describe alternatives you've considered**
The current state is solved by updating all instrumentation libraries as well as exporters, sdk, and utils.

**Additional context**
As @aabmass mentioned in the python slack channel, in the Go implementation this is targeted by a subdirectory for each version - https://pkg.go.dev/go.opentelemetry.io/otel/semconv

**Comment by srikanthccv** [comment] 2022-06-28 19:35
@nemoshlag Is your primary concern about the backwards compatibility or version conflict that arises when you installing new package?

**Comment by nemoshlag** [comment] 2022-06-29 10:34
Hi @srikanthccv thanks 🙏 version conflict is indeed my main issue - I've edited the issue accordingly

**Comment by tpadr** [comment] 2022-07-01 14:28
I have same circular dependency issue
```
  Because opentelemetry-instrumentation-fastapi (0.29b0) depends on opentelemetry-semantic-conventions (0.29b0)
   and opentelemetry-sdk (1.11.1) depends on opentelemetry-semantic-conventions (0.30b1), opentelemetry-instrumentation-fastapi (0.29b0) is incompatible with opentelemetry-sdk (1.11.1).
  So, because notebook-integration depends on both opentelemetry-sdk (1.11.1) and opentelemetry-instrumentation-fastapi (0.29b0), version solving failed.
```

**Comment by srikanthccv** [comment] 2022-07-01 14:42
Install `opentelemetry-instrumentation-fastapi` 0.30b1.

**Comment by tpadr** [comment] 2022-07-03 16:06
@srikanthccv here is my stack of `opentelemetry` libs, and I want updated them to the latest versions:
```
opentelemetry-api = "1.10.0"
opentelemetry-sdk = "1.10.0"
opentelemetry-instrumentation-fastapi = "0.29b0"
opentelemetry-instrumentation-httpx = "0.29b0"
opentelemetry-exporter-jaeger = "1.10.0"
opentelemetry-propagator-jaeger = "1.10.0"
```

When I try install `opentelemetry-instrumentation-fastapi==0.30b1`, I've got an error:
```
  Because opentelemetry-instrumentation-httpx (0.29b0) depends on opentelemetry-instrumentation (0.29b0)
   and opentelemetry-instrumentation-fastapi (0.30b1) depends on opentelemetry-instrumentation (0.30b1), opentelemetry-instrumentation-httpx (0.29b0) is incompatible with opentelemetry-instrumentation-fastapi (0.30b1).
  So, because notebook-integration depends on both opentelemetry-instrumentation-fastapi (0.30b1) and opentelemetry-instrumentation-httpx (0.29b0), version solving failed.
``` 

To fix this, I've tried install `opentelemetry-instrumentation-httpx==0.30b1` at first, but the process goes into infinite amount of time (freeze).
```PyPI: 1 packages found for opentelemetry-instrumentation-httpx 0.30b1

Updating dependencies
Resolving dependencies...
   1: fact: telemetry is 0.1.0
   1: derived: telemetry
   1: fact: telemetry depends on opentelemetry-instrumentation-httpx (0.30b1)
   1: selecting telemetry (0.1.0)
   1: derived: opentelemetry-instrumentation-httpx (==0.30b1)
PyPI: 1 packages found for opentelemetry-instrumentation-httpx 0.30b1
   1: fact: opentelemetry-instrumentation-httpx (0.30b1) depends on opentelemetry-api (>=1.3,<2.0)
   1: fact: opentelemetry-instrumentation-httpx (0.30b1) depends on opentelemetry-instrumentation (0.30b1)
   1: fact: opentelemetry-instrumentation-httpx (0.30b1) depends on opentelemetry-semantic-conventions (0.30b1)
   1: selecting opentelemetry-instrumentation-httpx (0.30b1)
   1: derived: opentelemetry-semantic-conventions (==0.30b1)
   1: derived: opentelemetry-instrumentation (==0.30b1)
   1: derived: opentelemetry-api (>=1.3,<2.0)
PyPI: 1 packages found for opentelemetry-semantic-conventions 0.30b1
```

**Comment by srikanthccv** [comment] 2022-09-09 17:31
@tpadr I couldn't reproduce the issue with pip, can you share which install tool you are using?

**Comment by tpadr** [comment] 2022-09-14 10:42
@srikanthccv, the issue is not reproducible anymore. I'm using poetry as package manager

**Comment by lzchen** [comment] 2022-09-20 16:29
Will be closing this issue. Feel free to comment if issue comes up again.

**Closed by lzchen** 2022-09-20 16:29 UTC
Labels: feature-request

**Comment by Kamalsky-dev** [comment] 2023-09-11 10:45
same error. can't fix.
