### ISSUE TITLE
LICENCE file missing from the opentelemetry-instrumentation-aio-pika

### ISSUE THREAD

**Issue by rahuldimri** [open-telemetry/opentelemetry-python-contrib#1219] opened 2022-08-08 12:12 UTC
LICENCE file missing from the below location:

[opentelemetry-instrumentation-aio-pika](https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-aio-pika)

**Comment by srikanthccv** [comment] 2022-08-08 12:36
Duplicate of https://github.com/open-telemetry/opentelemetry-python-contrib/issues/893

**Closed by srikanthccv** 2022-08-08 12:36 UTC
