### ISSUE TITLE
numerous `TypeError: __call__() missing 1 required positional argument: 'func'` when Django 500s

### ISSUE THREAD

**Issue by justmobilize** [open-telemetry/opentelemetry-python-contrib#827] opened 2021-12-08 03:06 UTC
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your Python version, [platform](https://docs.python.org/3/library/platform.html), version numbers of installed dependencies, information about your cloud hosting provider, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main.

`Python 3.8.10`

Requirments:
```
Django==2.2.24
django-object-actions==3.0.2
ipython==7.30.1
opentelemetry-api==1.7.1
opentelemetry-exporter-otlp-proto-grpc==1.7.1
opentelemetry-instrumentation-django==0.26b1
opentelemetry-instrumentation-requests==0.26b1
opentelemetry-sdk==1.7.1
psycopg2-binary==2.8.6
requests==2.26.0
```

**Steps to reproduce**
Describe exactly how to reproduce the error. Include a code sample if applicable.

Create basic Django application
Instrument:
```
    honeycomb_write_key = "xxxxxxxxxxxxxxxxxxxxxxx"
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "webapp.settings")
    resource = Resource(attributes={"service.name": "Service"})
    trace_provider = TracerProvider(resource=resource)
    otlp_exporter = OTLPSpanExporter(
        endpoint="api.honeycomb.io:443",
        insecure=False,
        credentials=ssl_channel_credentials(),
        headers=(("x-honeycomb-team", honeycomb_write_key), ("x-honeycomb-dataset", "Service")),
    )
    trace_provider.add_span_processor(BatchSpanProcessor(otlp_exporter))
    trace.set_tracer_provider(trace_provider)
    DjangoInstrumentor().instrument()
    RequestsInstrumentor().instrument()
```

Anywhere create something that will 500 in a view

**What is the expected behavior?**
What did you expect to see?

Normal 500 error, nothing additional 

**What is the actual behavior?**
What did you see instead?

numerous `TypeError: __call__() missing 1 required positional argument: 'func'`

```
Traceback (most recent call last):
  File "/opt/app/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/app/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/app/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/app/env/lib/python3.8/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/app/env/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/app/env/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/opt/app/env/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/app/env/lib/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/app/env/lib/python3.8/site-packages/django_object_actions/utils.py", line 260, in get
    ret = view(request, *self.view_args)
  File "/opt/app/test/test_app/admin.py", line 103, in resend_webhook
    y = x / 0
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/app/env/lib/python3.8/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
TypeError: __call__() missing 1 required positional argument: 'func'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/app/env/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/opt/app/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/opt/app/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/opt/app/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/opt/app/env/lib/python3.8/site-packages/django/views/debug.py", line 94, in technical_500_response
    html = reporter.get_traceback_html()
  File "/opt/app/env/lib/python3.8/site-packages/django/views/debug.py", line 334, in get_traceback_html
    return t.render(c)
  File "/opt/app/env/lib/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/opt/app/env/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/app/env/lib/python3.8/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/app/env/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/app/env/lib/python3.8/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/opt/app/env/lib/python3.8/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/app/env/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/app/env/lib/python3.8/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/opt/app/env/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/app/env/lib/python3.8/site-packages/django/template/base.py", line 987, in render
    output = self.filter_expression.resolve(context)
  File "/opt/app/env/lib/python3.8/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/opt/app/env/lib/python3.8/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/opt/app/env/lib/python3.8/site-packages/django/template/base.py", line 861, in _resolve_lookup
    getcallargs(current)
  File "/usr/lib/python3.8/inspect.py", line 1348, in getcallargs
    f_name = func.__name__
AttributeError: '_GeneratorContextManager' object has no attribute '__name__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app/env/lib/python3.8/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
TypeError: __call__() missing 1 required positional argument: 'func'
```

**Additional context**

Removing the `Instrumentation` works as expected. Not having a 500 logs correctly

**Comment by KypT** [comment] 2022-02-01 06:50
Having the same issue here, @justmobilize have you found any workaround for this problem?

**Comment by KypT** [comment] 2022-02-01 13:08
Only disabling standard `AdminEmailHandler` with combination with the parameters:
```
DEBUG = False
DEBUG_PROPAGATE_EXCEPTIONS = False
```
seems to work for me

**Comment by owais** [comment] 2022-02-01 13:34
Duplicate of #288

**Comment by owais** [comment] 2022-02-01 13:34
Closing this. Please add further comments to the other issue.

**Closed by owais** 2022-02-01 13:34 UTC
Labels: bug
