### ISSUE TITLE
ERROR: No matching distribution found for opentelemetry-instrumentation-aiohttp-server==0.42b0

### ISSUE THREAD

**Issue by sidrahate** [open-telemetry/opentelemetry-python-contrib#2053] opened 2023-11-09 10:06 UTC
Python Version - 3.8

**Steps to reproduce**
Using 'opentelemetry-bootstrap -a install' Command to Install the Dependencies for Auto Instrumentation.

**What is the expected behavior?**
package : opentelemetry-instrumentation-aiohttp-server==0.42b0 should be downloaded from pypi

**What is the actual behavior?**
ERROR: No matching distribution found for opentelemetry-instrumentation-aiohttp-server==0.42b0

**Comment by lzchen** [comment] 2023-11-09 19:11
There was an issue releasing the new version of `opentelemetry-instrumentation-aiohttp-server==0.42b0`, we are working on it to get it resolved.

**Comment by rubendv** [comment] 2023-11-15 13:19
We are also affected by this. We've removed opentelemetry instrumention temporarily as a workaround, but this is not an option for everybody of course.

**Comment by jkklapp** [comment] 2023-11-20 14:46
any updates on this issue?

**Comment by ronaldbradford** [comment] 2023-11-22 01:31
Receiving the same behaviour with 3.10.3

```
$ opentelemetry-bootstrap -a install
ERROR: Could not find a version that satisfies the requirement opentelemetry-instrumentation-aiohttp-server==0.42b0 (from versions: none)
ERROR: No matching distribution found for opentelemetry-instrumentation-aiohttp-server==0.42b0
```

**Comment by sidrahate** [comment] 2023-11-27 09:52
> There was an issue releasing the new version of `opentelemetry-instrumentation-aiohttp-server==0.42b0`, we are working on it to get it resolved.

Any ETA for this issue resolution.??
As we are forced to disable the instrumentation.

**Comment by tylerstar** [comment] 2023-12-05 06:25
This issue posted last month and still not working. At least to have a workaround before new version released.

**Comment by rubendv** [comment] 2023-12-07 14:09
We fixed it by downgrading to the previous version:

```
pip install opentelemetry-distro==0.41b0 opentelemetry-exporter-otlp==1.20.0
```

**Comment by slernercx** [comment] 2023-12-18 21:17
The above fix works- but would be great to have a complete fix and get back to reliable python install.

**Comment by j-bruce** [comment] 2023-12-20 00:20
I'm seeing this same error but with the `opentelemetry-instrumentation-aws-lambda==0.43b0` package

**Comment by phillipuniverse** [comment] 2023-12-20 02:19
Confirmed still broken in 0.43b0 for `opentelemetry-instrumentation-aiohttp-server`

**Comment by ocelotl** [comment] 2023-12-20 19:38
We have this issue because we can't release this package anymore to PyPi, we have reported it [here](https://github.com/pypi/support/issues/3353) already.

**Comment by ocelotl** [comment] 2023-12-20 19:41
I'm investigating a workaround for the time being, will report back here...

**Comment by vteran93** [comment] 2024-01-06 19:46
Someone forgot to add the folder to the package 0.43b0
![opentelemetry error](https://github.com/open-telemetry/opentelemetry-python-contrib/assets/1650359/d2334587-ad8d-4d92-ba66-79bdf47b81e9)

I was trying the workaround with the pyproject.tolm specification , but then i noticed that. Maybe the solution would be getting the commit that have the correct version

´´´
opentelemetry-instrumentation-aiohttp-server= {git = "https://github.com/open-telemetry/opentelemetry-python-contrib/",subdirectory="instrumentation/opentelemetry-instrumentation-aiohttp-server" ,tag = "v0.43b0"}
´´´

**Comment by GroomedGorilla** [comment] 2024-01-18 16:10
I'm getting the same error for `opentelemetry-instrumentation-aiohttp-server==0.43b0` when running `poetry run opentelemetry-bootstrap -a install`

Seems like it's a persistent issue 2 months on

**Comment by vteran93** [comment] 2024-01-20 04:15
This was my temporary solution in the project.toml

```tolm
opentelemetry-exporter-otlp = "^1.20.0"
opentelemetry-distro = "^0.41b0"
opentelemetry-exporter-jaeger = "^1.21.0"
```

**Comment by naisanzaa** [comment] 2024-01-30 04:25
Error is happening on: 

```shell
opentelemetry-distro>=0.43b0
opentelemetry-exporter-otlp>=1.22.0
```

**Comment by aabmass** [comment] 2024-01-30 19:15
Folks, please see https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2053#issuecomment-1865032194 this is an issue with PyPI. There is nothing we can do. You can definitely install from Git as mentioned in https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2053#issuecomment-1879799993

**Comment by viniciusd** [comment] 2024-01-31 03:58
> I was trying the workaround with the pyproject.tolm specification , but then i noticed that. Maybe the solution would be getting the commit that have the correct version
> 
> ```
> opentelemetry-instrumentation-aiohttp-server= {git = "https://github.com/open-telemetry/opentelemetry-python-contrib/",subdirectory="instrumentation/opentelemetry-instrumentation-aiohttp-server" ,tag = "v0.43b0"}
> ```

Wondering if any of you came up with a pip requirements.txt equivalent? I have been trying, without success:
```
git+https://github.com/open-telemetry/opentelemetry-python-contrib.git@v0.43b0#subdirectory=instrumentation/opentelemetry-instrumentation-aiohttp-server
```

**Comment by naisanzaa** [comment] 2024-01-31 07:37
> > I was trying the workaround with the pyproject.tolm specification , but then i noticed that. Maybe the solution would be getting the commit that have the correct version
> > ```
> > opentelemetry-instrumentation-aiohttp-server= {git = "https://github.com/open-telemetry/opentelemetry-python-contrib/",subdirectory="instrumentation/opentelemetry-instrumentation-aiohttp-server" ,tag = "v0.43b0"}
> > ```
> 
> Wondering if any of you came up with a pip requirements.txt equivalent? I have been trying, without success:
> 
> ```
> git+https://github.com/open-telemetry/opentelemetry-python-contrib.git@v0.43b0#subdirectory=instrumentation/opentelemetry-instrumentation-aiohttp-server
> ```

yeah I've been trying to figure that out and I don't see that as a solution anywhere here.

**Comment by naisanzaa** [comment] 2024-01-31 08:57
could someone just write the pip install command to run, and we can put all this behind us. I'm about to just take the folder out and make it into its own pypi

**Comment by aabmass** [comment] 2024-02-01 18:03
Thanks @naisanzaa this is real issue. It looks like the subdirectory was deleted in the git repo at the release tag as well. @ocelotl do you remember the context of https://github.com/open-telemetry/opentelemetry-python-contrib/commit/8c9df875e4bdbde95f22d874ee5be53ec7de3306?

**Comment by lzchen** [comment] 2024-02-01 18:08
@aabmass 

I believe we removed them manually from the commit since it was failing the release [build](https://github.com/open-telemetry/opentelemetry-python-contrib/actions/runs/7227861746/job/19696291312). The build fails as soon as an error occurs and the packages that need to be released after the order are ignored and not released properly. The temporary solution should just be ignoring those two specific packages from our release script, instead of removing them manually from the release commit.

**Comment by naisanzaa** [comment] 2024-02-01 18:14
> Thanks @naisanzaa this is real issue. It looks like the subdirectory was deleted in the git repo at the release tag as well. @ocelotl do you remember the context of https://github.com/open-telemetry/opentelemetry-python-contrib/commit/8c9df875e4bdbde95f22d874ee5be53ec7de3306?


Any chance to make an opentelemetry-python-contrib-hotfix pypi repo. And just update the scripts back once this 3 month ongoing problem fixes itself?

**Comment by aabmass** [comment] 2024-02-01 20:31
@lzchen to @naisanzaa's point, can we create a public git tag like `aiohttp-server-v0.43b0` at the parent commit (68bea0c10806056d4578446f8cb2167508094a21) so people can install it?

**Comment by naisanzaa** [comment] 2024-02-03 00:14
> @lzchen to @naisanzaa's point, can we create a public git tag like `aiohttp-server-v0.43b0` at the parent commit (68bea0c10806056d4578446f8cb2167508094a21) so people can install it?

This needs to be the solution today.

**Comment by ocelotl** [comment] 2024-02-05 23:24
I have added a new tag: [`0.43b0hotfix`](https://github.com/open-telemetry/opentelemetry-python-contrib/releases/tag/0.43b0hotfix). This can be used to install `opentelemetry-instrumentation-aiohttp-server` and `opentelemetry-resource-detector-container` with the following `pip` commands:

`pip install git+https://github.com/open-telemetry/opentelemetry-python-contrib.git@0.43b0hotfix#subdirectory=instrumentation/opentelemetry-instrumentation-aiohttp-server`
`pip install git+https://github.com/open-telemetry/opentelemetry-python-contrib.git@0.43b0hotfix#subdirectory=resource/opentelemetry-resource-detector-container`

**Comment by tammy-baylis-swi** [comment] 2024-02-23 19:16
Hi @ocelotl , could we also have a `0.44b0hotfix` tag following today's release?

**Comment by ocelotl** [comment] 2024-02-24 04:23
We may not need it, I think @lzchen fixed this issue

**Comment by naisanzaa** [comment] 2024-03-08 00:49
> We may not need it, I think @lzchen fixed this issue


I think we need to fix the tag. the tag should be `0.44b0` not `v0.44b0`


```
 % python3 -m pip install git+https://github.com/open-telemetry/opentelemetry-python-contrib.git#subdirectory=instrumentation/opentelemetry-instrumentation-aiohttp-server

Collecting git+https://github.com/open-telemetry/opentelemetry-python-contrib.git#subdirectory=instrumentation/opentelemetry-instrumentation-aiohttp-server
  Cloning https://github.com/open-telemetry/opentelemetry-python-contrib.git to /private/var/folders/sh/5g81k1ld671cw3xsn5269vv80000gn/T/pip-req-build-651y72to
  Running command git clone --filter=blob:none --quiet https://github.com/open-telemetry/opentelemetry-python-contrib.git /private/var/folders/sh/5g81k1ld671cw3xsn5269vv80000gn/T/pip-req-build-651y72to
  Resolved https://github.com/open-telemetry/opentelemetry-python-contrib.git to commit 565e78de2ca3b0304568ff01a70c614c3d4e8def
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: opentelemetry-api~=1.12 in /Users/eric/venv/automonisaur/lib/python3.11/site-packages (from opentelemetry-instrumentation-aiohttp-server==0.45b0.dev0) (1.23.0)
INFO: pip is looking at multiple versions of opentelemetry-instrumentation-aiohttp-server to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement opentelemetry-instrumentation==0.45b0.dev (from opentelemetry-instrumentation-aiohttp-server) (from versions: 0.9b0, 0.10b0, 0.11b0, 0.12b0, 0.13b0, 0.14b0, 0.15b0, 0.16b0, 0.16b1, 0.17b0, 0.18b0, 0.19b0, 0.20b0, 0.21b0, 0.22b0, 0.23b0, 0.23b1, 0.23b2, 0.24b0, 0.25b0, 0.25b1, 0.25b2, 0.26b1, 0.27b0, 0.28b0, 0.28b1, 0.29b0, 0.30b0, 0.30b1, 0.31b0, 0.32b0, 0.33b0, 0.34b0, 0.35b0, 0.36b0, 0.37b0, 0.38b0, 0.39b0, 0.40b0, 0.41b0, 0.42b0, 0.43b0, 0.44b0)
ERROR: No matching distribution found for opentelemetry-instrumentation==0.45b0.dev
```

**Comment by lzchen** [comment] 2024-03-08 19:25
@naisanzaa 

Not sure what you are referring to. You would still use `[0.43b0hotfix](https://github.com/open-telemetry/opentelemetry-python-contrib/releases/tag/0.43b0hotfix)` to install those packages. They were not included in the 0.44b0 release.

**Comment by lzchen** [comment] 2024-03-18 21:09
@npuichigo 

Above:

https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2053#issuecomment-1917720751

Until [this](https://github.com/pypi/support/issues/3353) is addressed, there is no long term solution. Please use the workaround in the meantime.

**Comment by viniciusd** [comment] 2024-04-03 16:26
Should we expect to have hotfix releases alike 0.43bhotfix or we shouldn't expect such tags as long as the root cause isn't fixed with pypi?

**Comment by viniciusd** [comment] 2024-04-10 22:48
@ocelotl From my understanding, #2101 is gonna patch this. Is that correct?

As in an `opentelemetry-contrib-instrumentation` installation will not even try to find the aiohttp instrumentation, so it shouldn't fail anymore. Those who don't depend on the aiohttp server instrumentation should then be able to successfully install `opentelemetry-contrib-instrumentation` out of the box. Is that interpretation right?

**Comment by doctorpangloss** [comment] 2024-04-12 19:38
> > I was trying the workaround with the pyproject.tolm specification , but then i noticed that. Maybe the solution would be getting the commit that have the correct version
> > ```
> > opentelemetry-instrumentation-aiohttp-server= {git = "https://github.com/open-telemetry/opentelemetry-python-contrib/",subdirectory="instrumentation/opentelemetry-instrumentation-aiohttp-server" ,tag = "v0.43b0"}
> > ```
> 
> Wondering if any of you came up with a pip requirements.txt equivalent? I have been trying, without success:
> 
> ```
> git+https://github.com/open-telemetry/opentelemetry-python-contrib.git@v0.43b0#subdirectory=instrumentation/opentelemetry-instrumentation-aiohttp-server
> ```

in requirements.txt:
```
opentelemetry-instrumentation-aiohttp-server @ git+https://github.com/open-telemetry/opentelemetry-python-contrib.git@v0.45b0#subdirectory=instrumentation/opentelemetry-instrumentation-aiohttp-server
```

**Closed** 2024-05-02 23:05 UTC
Labels: bug

**Comment by LeoQuote** [comment] 2024-05-13 05:59
Can we rename it to make it usable at least? When the 514 is fixed by pypa, we can place a dummy package for it. It's still complaining after 1 year.

**Comment by yanqianglu** [comment] 2024-05-30 17:27
Hi, I'm still having this issue with the new release 

```
Requirement already satisfied: deprecated>=1.2.6 in /Users/xx/.pyenv/versions/3.12.0/lib/python3.12/site-packages (from opentelemetry-api~=1.12->opentelemetry-instrumentation-aiohttp-client==0.45b0) (1.2.14)
Requirement already satisfied: importlib-metadata<=7.0,>=6.0 in /Users/xx/.pyenv/versions/3.12.0/lib/python3.12/site-packages (from opentelemetry-api~=1.12->opentelemetry-instrumentation-aiohttp-client==0.45b0) (7.0.0)
Requirement already satisfied: zipp>=0.5 in /Users/xx/.pyenv/versions/3.12.0/lib/python3.12/site-packages (from importlib-metadata<=7.0,>=6.0->opentelemetry-api~=1.12->opentelemetry-instrumentation-aiohttp-client==0.45b0) (3.19.0)
ERROR: Could not find a version that satisfies the requirement opentelemetry-instrumentation-aiohttp-server==0.45b0 (from versions: none)
ERROR: No matching distribution found for opentelemetry-instrumentation-aiohttp-server==0.45b0
Traceback (most recent call last):
  File "/Users/xx/.pyenv/versions/3.12.0/lib/python3.12/site-packages/opentelemetry/instrumentation/bootstrap.py", line 35, in wrapper
    return func(package)
           ^^^^^^^^^^^^^
  File "/Users/xx/.pyenv/versions/3.12.0/lib/python3.12/site-packages/opentelemetry/instrumentation/bootstrap.py", line 51, in _sys_pip_install
    subprocess.check_call(
  File "/Users/xx/.pyenv/versions/3.12.0/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/xx/.pyenv/versions/3.12.0/bin/python3.12', '-m', 'pip', 'install', '-U', '--upgrade-strategy', 'only-if-needed', 'opentelemetry-instrumentation-aiohttp-server==0.45b0']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred
```

**Comment by phillipuniverse** [comment] 2024-05-31 19:18
@ocelotl this still looks broken in 0.46b0

```
Because opentelemetry-contrib-instrumentations (0.46b0) depends on opentelemetry-instrumentation-aiohttp-server (0.46b0) which doesn't match any versions, opentelemetry-contrib-instrumentations is forbidden.
```

Happens when I have a dependency on 0.46b0

```
opentelemetry-contrib-instrumentations = { version = "0.46b0" }
```

Super easy to reproduce with:

```
pip install opentelemetry-contrib-instrumentations==0.46b0
```

Output:

```
~ » pip install opentelemetry-contrib-instrumentations==0.46b0                                                                                                                       [14:16:44]
Collecting opentelemetry-contrib-instrumentations==0.46b0
  Downloading opentelemetry_contrib_instrumentations-0.46b0-py3-none-any.whl (6.6 kB)
Collecting opentelemetry-instrumentation-aws-lambda==0.46b0
  Downloading opentelemetry_instrumentation_aws_lambda-0.46b0-py3-none-any.whl (12 kB)
Collecting opentelemetry-instrumentation-sqlalchemy==0.46b0
  Downloading opentelemetry_instrumentation_sqlalchemy-0.46b0-py3-none-any.whl (13 kB)
Collecting opentelemetry-instrumentation-asgi==0.46b0
  Downloading opentelemetry_instrumentation_asgi-0.46b0-py3-none-any.whl (14 kB)
Collecting opentelemetry-instrumentation-tortoiseorm==0.46b0
  Downloading opentelemetry_instrumentation_tortoiseorm-0.46b0-py3-none-any.whl (10 kB)
Collecting opentelemetry-instrumentation-django==0.46b0
  Downloading opentelemetry_instrumentation_django-0.46b0-py3-none-any.whl (18 kB)
Collecting opentelemetry-instrumentation-remoulade==0.46b0
  Downloading opentelemetry_instrumentation_remoulade-0.46b0-py3-none-any.whl (10 kB)
Collecting opentelemetry-instrumentation-aio-pika==0.46b0
  Downloading opentelemetry_instrumentation_aio_pika-0.46b0-py3-none-any.whl (13 kB)
Collecting opentelemetry-instrumentation-logging==0.46b0
  Downloading opentelemetry_instrumentation_logging-0.46b0-py3-none-any.whl (12 kB)
Collecting opentelemetry-instrumentation-redis==0.46b0
  Downloading opentelemetry_instrumentation_redis-0.46b0-py3-none-any.whl (11 kB)
Collecting opentelemetry-instrumentation-mysql==0.46b0
  Downloading opentelemetry_instrumentation_mysql-0.46b0-py3-none-any.whl (8.8 kB)
Collecting opentelemetry-instrumentation-confluent-kafka==0.46b0
  Downloading opentelemetry_instrumentation_confluent_kafka-0.46b0-py3-none-any.whl (12 kB)
Collecting opentelemetry-instrumentation-wsgi==0.46b0
  Downloading opentelemetry_instrumentation_wsgi-0.46b0-py3-none-any.whl (13 kB)
Collecting opentelemetry-instrumentation-flask==0.46b0
  Downloading opentelemetry_instrumentation_flask-0.46b0-py3-none-any.whl (14 kB)
Collecting opentelemetry-instrumentation-pymongo==0.46b0
  Downloading opentelemetry_instrumentation_pymongo-0.46b0-py3-none-any.whl (10 kB)
Collecting opentelemetry-instrumentation-asyncio==0.46b0
  Downloading opentelemetry_instrumentation_asyncio-0.46b0-py3-none-any.whl (13 kB)
Collecting opentelemetry-instrumentation-pika==0.46b0
  Downloading opentelemetry_instrumentation_pika-0.46b0-py3-none-any.whl (13 kB)
Collecting opentelemetry-instrumentation-pymysql==0.46b0
  Downloading opentelemetry_instrumentation_pymysql-0.46b0-py3-none-any.whl (8.7 kB)
ERROR: Could not find a version that satisfies the requirement opentelemetry-instrumentation-aiohttp-server==0.46b0 (from opentelemetry-contrib-instrumentations) (from versions: none)
ERROR: No matching distribution found for opentelemetry-instrumentation-aiohttp-server==0.46b0
```

**Comment by pmcollins** [comment] 2024-06-04 18:03
Has changing the name of the package in pyproject.toml been discussed? e.g. from `opentelemetry-instrumentation-aiohttp-server` to `opentelemetry-instrumentation-aiohttp-server-v2 `or something.

**Comment by decko** [comment] 2024-06-17 20:58
> Has changing the name of the package in pyproject.toml been discussed? e.g. from `opentelemetry-instrumentation-aiohttp-server` to `opentelemetry-instrumentation-aiohttp-server-v2` or something

Do we have any logs about this conversation? Why changing the name?

**Comment by emdneto** [comment] 2024-06-18 13:01
@decko I don't think this has been discussed yet

**Comment by viniciusd** [comment] 2024-06-18 13:05
> Do we have any logs about this conversation? Why changing the name?

This thread itself, it has been suggested in the thread as well, but it hasn't been discussed. The problem it would be trying to solve is the issue in this thread. `opentelemetry-instrumentation-aiohttp-server` isn't being published because of an issue with pypi (pypi/support#3353)

**Comment by ocelotl** [comment] 2024-06-20 16:34
There is a related issue reported here: https://github.com/pypi/support/issues/3353

**Comment by Rehaan1** [comment] 2024-06-21 08:54
Use

```
 pip install git+https://github.com/open-telemetry/opentelemetry-python-contrib.git@v0.45b0#subdirectory=instrumentation/opentelemetry-instrument
ation-aiohttp-server
```

**Comment by emdneto** [comment] 2024-07-18 21:53
PyPi issue is solved https://github.com/pypi/support/issues/3353
