### ISSUE TITLE
Instrumentation support for CherryPy Framework

### ISSUE THREAD

**Issue by TheAnshul756** [open-telemetry/opentelemetry-python-contrib#1360] opened 2022-09-28 11:34 UTC

**Comment by TheAnshul756** [comment] 2022-09-28 11:34
Please assign this to me.

**Comment by srikanthccv** [comment] 2022-09-28 11:47
Duplicate of #1130

**Closed by srikanthccv** 2022-09-28 11:47 UTC
Labels: feature-request

**Comment by srikanthccv** [comment] 2022-09-28 11:54
Add a comment there. I will assign it to you.
