### ISSUE TITLE
MANIFEST file missing form the opentelemetry-instrumentation-aio-pika/

### ISSUE THREAD

**Issue by rahuldimri** [open-telemetry/opentelemetry-python-contrib#1221] opened 2022-08-08 12:19 UTC
Manifest file missing from the location:

[opentelemetry-python-contrib](https://github.com/open-telemetry/opentelemetry-python-contrib)/[instrumentation](https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation)/opentelemetry-instrumentation-aio-pika/

**Comment by srikanthccv** [comment] 2022-08-08 12:37
Duplicate of https://github.com/open-telemetry/opentelemetry-python-contrib/issues/893

**Closed by srikanthccv** 2022-08-08 12:37 UTC
