### ISSUE TITLE
No package released for opentelemetry-instrumentation-aiohttp-server

### ISSUE THREAD

**Issue by joshight** [open-telemetry/opentelemetry-python-contrib#2488] opened 2024-05-02 19:10 UTC
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your Python version, [platform](https://docs.python.org/3/library/platform.html), version numbers of installed dependencies, information about your cloud hosting provider, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main.

aiohttp-client (along with the other instrumentation pkgs) is here: https://pypi.org/simple/opentelemetry-instrumentation-aiohttp-client/, but https://pypi.org/simple/opentelemetry-instrumentation-aiohttp-server does not exist. 

Can version 0.45b0 of opentelemetry-instrumentation-aiohttp-server be released/uploaded to pypi? 

**Steps to reproduce**
Describe exactly how to reproduce the error. Include a code sample if applicable.

pip install opentelemetry-instrumentation-aiohttp-server

**What is the expected behavior?**
What did you expect to see?

Package downloaded/installed

**What is the actual behavior?**
What did you see instead?

$ pip install opentelemetry-instrumentation-aiohttp-server

ERROR: Could not find a version that satisfies the requirement opentelemetry-instrumentation-aiohttp-server (from versions: none)
ERROR: No matching distribution found for opentelemetry-instrumentation-aiohttp-server

**Additional context**

**Comment by LeoQuote** [comment] 2024-05-14 14:13
Duplicate of https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2053

**Closed** 2024-05-22 14:21 UTC
Labels: bug
