### ISSUE TITLE
tox test will fail on aiottp-client, boto and cassandra instrumentation

### ISSUE THREAD

**Issue by zhihali** [open-telemetry/opentelemetry-python-contrib#2707] opened 2024-07-14 22:46 UTC
### Describe your environment

OS: (e.g, Ubuntu)
Python version: (e.g., Python 3.8.10)
Package version: (e.g., 0.46.0)

### What happened?

when running 
`tox -e py312-test-instrumentation-aiohttp-client `
`tox -e py312-test-instrumentation-boto`
`tox -e py312-test-instrumentation-cassandra`

the test will not pass.

### Steps to Reproduce

run 
`tox -e py312-test-instrumentation-aiohttp-client `
`tox -e py312-test-instrumentation-boto`
`tox -e py312-test-instrumentation-cassandra`

### Expected Result

all tests pass

### Actual Result

some are failed

### Would you like to implement a fix?

Yes

**Comment by emdneto** [comment] 2024-07-14 23:45
Which error are you getting? Are you getting something different from what's in CI?

**Comment by emdneto** [comment] 2024-07-23 15:24
Closing as tests are working fine, and we're not able to reproduce the issue

**Closed** 2024-07-23 15:24 UTC
Labels: bug
