### ISSUE TITLE
Missing Prometheus Remote-Write Exporter Code

### ISSUE THREAD

**Issue by rltoSD** [open-telemetry/opentelemetry-python-contrib#824] opened 2021-12-07 02:40 UTC
As mentioned here in issue #2291 on [opentelemetry-python ](https://github.com/open-telemetry/opentelemetry-python/issues/2291), the code for the Prometheus Remote-Write Exporter is missing from the repo. This is a big issue because the source code is not located anywhere on github. 

AWS Engineers had contributed to developing the PRW exporter 
https://aws.amazon.com/blogs/opensource/building-a-prometheus-remote-write-exporter-for-the-opentelemetry-python-sdk/

**Comment by ocelotl** [comment] 2021-12-07 18:24
This is a duplicate of [#2291](https://github.com/open-telemetry/opentelemetry-python/issues/2291), I suggest closing this issue, @open-telemetry/opentelemetry-python-contrib-approvers.

We should not have an issue tracking the missing Prometheus exporter in contrib because the [Prometheus exporter will not exist in contrib but in core](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/81#issuecomment-714885713).

@rltoSD, please refer to [#2291](https://github.com/open-telemetry/opentelemetry-python/issues/2291) for more information.

**Closed** 2021-12-08 02:18 UTC
Labels: feature-request
